name: Build Magic Contracts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v7.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy
        pip install kivy_deps.sdl2 kivy_deps.glew kivy_deps.angle
        pip install pyinstaller
        pip install python-docx docxtpl
    
    - name: Build EXE
      env:
        CI: 1
        KIVY_NO_ARGS: 1
        KIVY_GL_BACKEND: angle_sdl2
      run: |
        python -m PyInstaller --name MagicContracts --noconsole --icon=assets/icon.ico --add-data "src/formularz.kv;." --add-data "assets;assets/" --add-binary "C:/hostedtoolcache/windows/Python/3.12.7/x64/python312.dll;." src/main.py

    - name: List dist directory
      run: dir dist

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MagicContracts
        path: dist/MagicContracts/MagicContracts.exe

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/MagicContracts/MagicContracts.exe
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}