name: Build EXE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy
        pip install kivy_deps.sdl2 kivy_deps.glew kivy_deps.angle
        pip install pyinstaller
    
    - name: Build EXE
      env:
        KIVY_GL_BACKEND: 'angle_sdl2'
      run: |
        pyinstaller --name=ContractGenerator `
          --onefile `
          --windowed `
          --add-data "assets;assets" `
          --add-data "src/formularz.kv;." `
          --hidden-import "win32timezone" `
          --collect-all "kivy" `
          src/main.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ContractGenerator
        path: dist/ContractGenerator.exe