name: Build EXE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy
        pip install kivy_deps.sdl2 kivy_deps.glew kivy_deps.angle
        pip install pyinstaller
        pip install python-docx docxtpl
    
    - name: Build EXE
      env:
        KIVY_GL_BACKEND: 'angle_sdl2'
      shell: cmd
      run: pyinstaller --name=ContractGenerator --onefile --windowed --add-data "assets;assets" --add-data "src/formularz.kv;." --hidden-import win32timezone --hidden-import kivy --hidden-import kivy.deps.sdl2 --hidden-import kivy.deps.glew --hidden-import kivy.deps.angle --hidden-import kivy.factory_registers --hidden-import kivy.graphics --hidden-import kivy.core.window --hidden-import kivy.core.text --hidden-import kivy.core.image --hidden-import docxtpl src/main.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ContractGenerator
        path: dist/ContractGenerator.exe