name: Build Magic Contracts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Generate version number
      id: tag_version
      run: |
        echo "new_tag=$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_OUTPUT
      shell: bash
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy
        pip install kivy_deps.sdl2 kivy_deps.glew kivy_deps.angle
        pip install pyinstaller
        pip install python-docx docxtpl
    
    - name: Build EXE
      env:
        KIVY_GL_BACKEND: 'angle_sdl2'
      shell: cmd
      run: pyinstaller --name=ContractGenerator --onefile --windowed --add-data "src/formularz.kv;." --hidden-import win32timezone --hidden-import kivy --hidden-import kivy.deps.sdl2 --hidden-import kivy.deps.glew --hidden-import kivy.deps.angle --hidden-import kivy.factory_registers --hidden-import kivy.graphics --hidden-import kivy.core.window --hidden-import kivy.core.text --hidden-import kivy.core.image --hidden-import docxtpl --hidden-import kivy.uix.checkbox --hidden-import kivy.uix.textinput --hidden-import kivy.uix.boxlayout --hidden-import kivy.uix.gridlayout --hidden-import kivy.uix.label --hidden-import kivy.uix.button src/main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ContractGenerator
        path: dist/ContractGenerator.exe

    - name: Create Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "v${{ steps.tag_version.outputs.new_tag }}" ./dist/ContractGenerator.exe --title "Release ${{ steps.tag_version.outputs.new_tag }}" --notes "Automatyczne wydanie z dnia ${{ steps.tag_version.outputs.new_tag }}"